Fix HTTP NTLM type 3 output
Trying to print a tuple lead to "not all arguments converted during string formatting" error:
```Python 2.7.16
>>> a = 1,2
>>> print "%s"%a
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: not all arguments converted during string formatting
```

Fix this by adding missing [0]